

try {
    throw new Error('error msg')
} catch(err) {
    console.log(err, 'err')
}